-- V1_0__Create_all_tables.sql

-- Erstellt die Tabelle für Länder
CREATE TABLE country (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_country_name UNIQUE (name)
);

-- Erstellt die Tabelle für CO₂-Emissionsdaten
CREATE TABLE co2_data (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id     BIGINT NOT NULL,
    emission_year  INT    NOT NULL,
    co2_kt         BIGINT NOT NULL,

    CONSTRAINT fk_co2_country
        FOREIGN KEY (country_id)
            REFERENCES country (id)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT,

    -- Pro Land nur ein Datensatz pro Jahr (Unique Constraint)
    CONSTRAINT uk_co2_country_year UNIQUE (country_id, emission_year)
);

-- Hilfreiche Indizes für schnelle Abfragen nach Land/Jahr
CREATE INDEX idx_country_name ON country (name);
CREATE INDEX idx_co2_country ON co2_data (country_id);
CREATE INDEX idx_co2_year ON co2_data (emission_year);